# -*- coding: utf-8 -*-
"""Assignment 03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnQC9fjHRGExC1j2MMYIixJ6_4vSUYQ8
"""

#........ and shoot for the Sky in you getting a big promotion & opportunity
#DolapoOdebiyi
print("Dolapo Odebiyi:")
fname = input("fname")#Dolapo
lname = input("lname") #Odebiyi
fullnames = fname + " " + lname

#Enter phone, email
print("+17133075420")
phone = input("number")
print("itzdolarp406@gmail.com")
email = input("email")

#price of a used car
price = 10000
has_good_credit = True;

if has_good_credit:
    down_payment = 0.1 * 10000
else:
    down_payment = 0.2 * 10000

print("down payment")
print('1000')
print("Dolapo Odebiyi")
print(+17133075420)
print("itzdolarp406@gmail.com")
print(0.1 * 10000)